on:
    push:
      branches:
        - main
    workflow_dispatch:
  
name: Build website 

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
# Build job
  build_project:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1 
          with:
            working-directory: Website
            ruby-version: '3.1' # Not needed with a .ruby-version file
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            cache-version: 0 # Increment this number if you need to re-download cached gems
        - name: Bundle website
          working-directory: Website
          run: JEKYLL_ENV=production bundle exec jekyll build

        - name: Upload Website & blueprint artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path:  Website/_site

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4